import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import Navigation from "@/components/marketing/Navigation";
import NavigationMobile from "@/components/marketing/NavigationMobile";
import Footer from "@/components/marketing/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <div className=" md:block hidden">
              <Navigation />
            </div>
            <div className=" md:hidden block">
              <NavigationMobile />
            </div>
          </div>
          {children}

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
